#!/usr/bin/env bash

# Run via
# bash ./utils/update-phar <output directory>
# @example bash ./utils/update-phar E:/OneDrive/scripts/wordpress

set -ex

version=$2
if [[""=${version}]]; then
	version="same"
fi
current_rev=$(git rev-parse HEAD)
current_rev=${current_rev:0:10}

##passed on the command line
packages_repo=$1

fname="wp-cli.phar"

# generate archive
php -dphar.readonly=0 ./utils/make-phar.php $packages_repo/$fname --quiet --version=$version --store-version

cd $packages_repo

# smoke test
php $fname --version
